on:
  push:
    branches:
      - next
env:
  IS_ACTIONS_DOC: "false"

jobs:
  rebuild-docs:
    name: Build new actiondoc
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment
        run: |
          chmod +x ci/setvars.sh
          ci/setvars.sh
      - name: Publish docs
        env:
          BOT_USER: ${{ secrets.BOT_INIT_USER }}
          BOT_MAIL: ${{ secrets.BOT_INIT_MAIL }}
          BOT_API: ${{ secrets.BOT_API_CALL }}
          GIT_SHA: ${{ env.GITHUB_SHA }}
        run: |
          chmod +x ci/doc.sh
          ci/doc.sh
        if: env.IS_ACTIONS_DOC == 'true'
